routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('welcome');
})->name('login');

Route::get('/', function () {
    $user = \App\Models\User::find(1);
    ray()->model($user);
    return view('winddown');
})->name('winddown');

Route::post('/', '\App\Http\Controllers\UserController@login')->name('login.post');
Route::post('/password-update', '\App\Http\Controllers\UserController@passwordUpdate')->name('password.update');
Route::get('/logout', '\App\Http\Controllers\UserController@logout')->name('logout');

Route::get('/signup', '\App\Http\Controllers\UserController@signup')->name('signup');
Route::post('/signup', '\App\Http\Controllers\UserController@validateUser')->name('signup.validate');
Route::get('/signup/password', '\App\Http\Controllers\UserController@password')->name('signup.password');
Route::get('/signup/{user}/password', '\App\Http\Controllers\UserController@passwordWithUser')->name('signup.password-with-user');
Route::post('/signup/password', '\App\Http\Controllers\UserController@passwordSave')->name('signup.password.save');

Route::get('/faq', '\App\Http\Controllers\UserController@faq')->name('faq');
Route::get('/request', '\App\Http\Controllers\UserController@request')->name('request');
Route::post('/request-post', '\App\Http\Controllers\UserController@requestPost')->name('request.post');
Route::get('/request-sent', '\App\Http\Controllers\UserController@requestSent')->name('request.sent');
Route::get('/validate-email/check/{token}', '\App\Http\Controllers\UserController@validateEmailTemp')->name('signup.validate-email-temp');
Route::get('/validate-email/{token}', '\App\Http\Controllers\UserController@validateEmail')->name('signup.validate-email');
Route::get('/signup-error', '\App\Http\Controllers\UserController@signupError')->name('signup.error');
Route::get('/use-code', '\App\Http\Controllers\UserController@signupWithCode')->name('signup.code');
Route::post('/use-code', '\App\Http\Controllers\UserController@signupWithCodePost')->name('signup.code.post');

Route::middleware(['auth'])->group(function(){
    Route::get('/dashboard', '\App\Http\Controllers\UserController@dashboard')->name('dashboard');
    Route::get('/download/{file}', '\App\Http\Controllers\UserController@download')->name('download');
    Route::get('/profile', '\App\Http\Controllers\UserController@profile')->name('profile');
    Route::get('/questions', '\App\Http\Controllers\QuestionController@index')->name('questions');
    Route::get('/questions/ask', '\App\Http\Controllers\QuestionController@ask')->name('questions.ask');
    Route::post('/questions', '\App\Http\Controllers\QuestionController@save')->name('questions.save');
    Route::get('/questions/{question}', '\App\Http\Controllers\QuestionController@view')->name('questions.view')->middleware(['auth']);
    Route::get('/faq-auth', '\App\Http\Controllers\UserController@faqAuth')->name('faq-auth');
});

Route::get('/admin/login', function () {
    return view('admin.login');
})->name('admin.login');

Route::post('/admin/login', '\App\Http\Controllers\AdminController@login')->name('admin.login.post');
Route::get('/admin/logout', '\App\Http\Controllers\AdminController@logout')->name('admin.logout');

Route::prefix('admin')->middleware('auth.admin')->group(function () {
    Route::get('/', '\App\Http\Controllers\AdminController@dashboard')->name('admin.dashboard');
    Route::post('/upload', '\App\Http\Controllers\FileController@upload')->name('admin.upload');
    Route::get('/delete/{file}', '\App\Http\Controllers\FileController@delete')->name('admin.delete');
    Route::get('/requests', '\App\Http\Controllers\RequestController@index')->name('admin.requests');
    Route::get('/requests/{user}/approve', '\App\Http\Controllers\RequestController@approve')->name('admin.requests.approve');
    Route::get('/requests/{user}/generate', '\App\Http\Controllers\RequestController@generate')->name('admin.requests.generate');
    Route::post('/requests/generate', '\App\Http\Controllers\RequestController@generateMass')->name('admin.requests.generate-mass');
    Route::get('/users', '\App\Http\Controllers\UserController@adminIndex')->name('admin.users');
    Route::get('/users/{user}', '\App\Http\Controllers\UserController@adminEdit')->name('admin.users.edit');
    Route::post('/users/{user}', '\App\Http\Controllers\UserController@adminUpdate')->name('admin.users.update');
    Route::get('/users/{user}/delete', '\App\Http\Controllers\UserController@adminDelete')->name('admin.users.delete');
    Route::get('/users/{user}/history', '\App\Http\Controllers\UserController@history')->name('admin.users.history');
    Route::get('/roles', '\App\Http\Controllers\PermissionController@index')->name('admin.roles');
    Route::post('/roles', '\App\Http\Controllers\PermissionController@save')->name('admin.roles.save');
    Route::post('/roles/{role}', '\App\Http\Controllers\PermissionController@update')->name('admin.roles.update');
    Route::get('/faq', '\App\Http\Controllers\FaqController@index')->name('admin.faq');
    Route::get('/faq/create', '\App\Http\Controllers\FaqController@create')->name('admin.faq.create');
    Route::post('/faq', '\App\Http\Controllers\FaqController@save')->name('admin.faq.save');
    Route::get('/faq/{faq}', '\App\Http\Controllers\FaqController@edit')->name('admin.faq.edit');
    Route::post('/faq/{faq}', '\App\Http\Controllers\FaqController@update')->name('admin.faq.update');
    Route::get('/faq/{faq}/delete', '\App\Http\Controllers\FaqController@delete')->name('admin.faq.delete');
    Route::get('/questions', '\App\Http\Controllers\QuestionController@adminIndex')->name('admin.questions');
    Route::get('/questions/history', '\App\Http\Controllers\QuestionController@history')->name('admin.questions.history');
    Route::get('/questions/{question}/view', '\App\Http\Controllers\QuestionController@adminView')->name('admin.questions.view');
    Route::get('/questions/{question}', '\App\Http\Controllers\QuestionController@answer')->name('admin.questions.answer');
    Route::post('/questions/{question}', '\App\Http\Controllers\QuestionController@saveAnswer')->name('admin.questions.answer.save');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use HasFactory, Notifiable;
    use SoftDeletes;

    protected $dates = ['request_date'];

    protected $fillable = [
        'name',
        'email',
        'password'
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    function getFirstNameAttribute(): string
    {
        return explode(" ", $this->name)[0];
    }

    public function getInitialsAttribute(): string
    {
        $name_array = explode(' ',trim($this->name));

        $firstWord = $name_array[0];
        $lastWord = $name_array[count($name_array)-1];

        return Str::upper($firstWord[0]."".$lastWord[0]);
    }

    function logs(){
        return $this->hasMany('\App\Models\Log');
    }
}

resources/views/_menu.blade.php
<nav class="flex-1 flex flex-col overflow-y-auto" aria-label="Sidebar">
    <div class="px-2 space-y-1">
        <a href="{{ route('faq-auth') }}" class="@if(request()->routeIs('faq*')) bg-lime-800 @endif text-white group flex items-center px-2 py-2 text-sm leading-6 font-medium rounded-md text-lime-100 hover:text-white hover:bg-lime-600">
            <svg xmlns="http://www.w3.org/2000/svg" class="mr-4 h-6 w-6 text-lime-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
            </svg>
            FAQ
        </a>
    </div>
    <div class="px-2 space-y-1">
        <a href="{{ route('questions') }}" class="@if(request()->routeIs('questions*')) bg-lime-800 @endif text-white group flex items-center px-2 py-2 text-sm leading-6 font-medium rounded-md text-lime-100 hover:text-white hover:bg-lime-600">
            <!-- Heroicon name: document-report -->
            <svg xmlns="http://www.w3.org/2000/svg" class="mr-4 h-6 w-6 text-lime-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z" />
            </svg>
            My Questions
        </a>
    </div>
    <div class="mt-6 pt-6 border-t border-lime-800">
        <div class="px-2 space-y-1">
            <a href="{{ route('profile') }}" class="@if(request()->routeIs('profile')) bg-lime-800 @endif group flex items-center px-2 py-2 text-sm leading-6 font-medium rounded-md text-lime-100 hover:text-white hover:bg-lime-600">
                <!-- Heroicon name: cog -->
                <svg class="mr-4 h-6 w-6 text-lime-200" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
                Profile
            </a>

            <a href="{{ route('logout') }}" class="group flex items-center px-2 py-2 text-sm leading-6 font-medium rounded-md text-lime-100 hover:text-white hover:bg-lime-600">
                <!-- Heroicon name: shield-check -->
                <svg class="mr-4 h-6 w-6 text-lime-200" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                </svg>
                Logout
            </a>
        </div>
    </div>
</nav>

resources/views/dashboard.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Trustee Registration Portal</title>

        <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="antialiased">
    <!--
  This example requires Tailwind CSS v2.0+

  This example requires some changes to your config:

  ```
  // tailwind.config.js
  const colors = require('tailwindcss/colors')

  module.exports = {
    // ...
    theme: {
      extend: {
        colors: {
          lime: colors.lime,
        }
      }
    },
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ]
  }
  ```
-->
    <!-- This example requires Tailwind CSS v2.0+ -->
    <div class="fixed z-10 inset-0 overflow-y-auto hidden" id="modal" aria-labelledby="modal-title" role="dialog" aria-modal="true">
        <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
            <!--
              Background overlay, show/hide based on modal state.

              Entering: "ease-out duration-300"
                From: "opacity-0"
                To: "opacity-100"
              Leaving: "ease-in duration-200"
                From: "opacity-100"
                To: "opacity-0"
            -->
            <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>

            <!-- This element is to trick the browser into centering the modal contents. -->
            <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

            <!--
              Modal panel, show/hide based on modal state.

              Entering: "ease-out duration-300"
                From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                To: "opacity-100 translate-y-0 sm:scale-100"
              Leaving: "ease-in duration-200"
                From: "opacity-100 translate-y-0 sm:scale-100"
                To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            -->
            <div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full sm:p-6">
                <div>
                    <div class="mt-3 text-center sm:mt-5">
                        <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">
                            Important
                        </h3>
                    </div>
                </div>
                <div>
                    <div class="relative flex mt-4">
                        <div class="flex items-center h-5">
                            <input onclick="validate()" id="consent" name="comments" type="checkbox" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-500 rounded">
                        </div>
                        <div class="ml-3 text-sm">
                            <label for="comments" class="font-medium text-gray-700">By checking this box, I acknowledge that I am a Keep Policy Investor in accordance with the Mutual Benefits Keep Policy Trust dated September 25, 2009.</label>
                        </div>
                    </div>
                </div>
                <div class="mt-5 sm:mt-6 sm:grid sm:grid-cols-2 sm:gap-3 sm:grid-flow-row-dense">
                    <a href="#" type="button" id="consent-button" class="opacity-50 w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-lime-600 text-base font-medium text-white hover:bg-lime-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-lime-500 sm:col-start-2 sm:text-sm">
                        Download
                    </a>
                    <button onclick="hide()" type="button" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:col-start-1 sm:text-sm">
                        Cancel
                    </button>
                </div>
            </div>
        </div>
    </div>


    <div class="h-screen flex overflow-hidden bg-gray-100">
        <div class="hidden lg:flex lg:flex-shrink-0">
            <div class="flex flex-col w-64">
                <!-- Sidebar component, swap this element with another sidebar if you like -->
                <div class="flex flex-col flex-grow bg-lime-700 pt-5 pb-4 overflow-y-auto">
                    @include('_menu')
                </div>
            </div>
        </div>

        <div class="flex-1 overflow-auto focus:outline-none" tabindex="0">

            <main class="flex-1 relative pb-8 z-0 overflow-y-auto">
                <!-- Page header -->
                <div class="bg-white shadow">
                    <div class="px-4 sm:px-6 lg:max-w-6xl lg:mx-auto lg:px-8">
                        <div class="py-6 md:flex md:items-center md:justify-between lg:border-t lg:border-gray-200">
                            <div class="flex-1 min-w-0">
                                <!-- Profile -->
                                <div class="flex items-center justify-between">
                                    <div>
                                        <img src="{{ asset('images/logo.jpg') }}" alt="">
                                    </div>

                                    <div class="flex items-center">
                                        <span class="inline-flex items-center justify-center h-14 w-14 rounded-full bg-gray-500">
                                          <span class="text-xl font-medium leading-none text-white">{{ Auth::user()->initials }}</span>
                                        </span>

                                        <div>
                                            <div class="flex items-center">
                                                <h1 class="ml-3 text-2xl font-light leading-7 text-gray-700 sm:leading-7 sm:truncate">
                                                    {{ Auth::user()->name }}
                                                </h1>
                                            </div>
                                            <dl class="mt-6 flex flex-col sm:ml-3 sm:mt-1 sm:flex-row sm:flex-wrap">
                                                <dd class="mt-3 flex items-center text-sm text-gray-500 font-medium sm:mr-6 sm:mt-0 capitalize">
                                                    Investor number {{ Auth::user()->investor_number }}
                                                </dd>
                                            </dl>
                                        </div>


                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="p-6">
                    <h2 class="max-w-6xl  mt-8 mb-6 text-lg leading-6 font-medium text-gray-900">
                        Available documents
                    </h2>

                    @if(!Auth::user()->isAbleTo('Download Financial Record'))
                        <div class="flex items-center text-red-600">
                            <svg class="h-6 w-6 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                            </svg>

                            <div>
                                You are not allowed to access documents at this moment.
                            </div>
                        </div>
                    @else
                        @if($files->isEmpty())
                            <div class="flex items-center text-red-600">
                                <svg class="h-6 w-6 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                                </svg>

                                <div>
                                    No documents found.
                                </div>
                            </div>
                        @else

                            <div class="flex flex-col mt-2">
                                <div class="align-middle min-w-full overflow-x-auto shadow overflow-hidden sm:rounded-lg">
                                    <table class="min-w-full divide-y divide-gray-200">
                                        <thead>
                                        <tr>
                                            <th class="whitespace-nowrap px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Document name
                                            </th>
                                            <th class="whitespace-nowrap px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Document type
                                            </th>
                                            <th class="whitespace-nowrap px-6 py-3 bg-gray-50 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Last updated
                                            </th>
                                            <th class="whitespace-nowrap px-6 py-3 bg-gray-50 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                &nbsp;
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody class="bg-white divide-y divide-gray-200">

                                        @foreach($files as $file)
                                            <tr class="bg-white">
                                                <td class="max-w-0 w-full px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    {{ $file->name }}
                                                </td>
                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                                    {{ \Illuminate\Support\Str::upper($file->extension) }}
                                                </td>
                                                <td class="px-6 py-4 text-right whitespace-nowrap text-sm text-gray-500">
                                                    {{ $file->created_at->format("m-d-Y") }}
                                                </td>
                                                <td class="px-6 py-4 text-right whitespace-nowrap text-sm">
                                                    <a target="_blank" onclick="consent('{{ route('download', $file->id) }}')" class="cursor-pointer text-lime-600 font-medium underline">Download</a>
                                                </td>
                                            </tr>
                                        @endforeach

                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        @endif

                    @endif

                </div>
            </main>
        </div>
    </div>

    <script type="text/javascript">
        function consent(url){
            document.getElementById('modal').classList.remove('hidden');
            document.getElementById('consent-button').dataset.url = url;
        }

        function hide(){
            document.getElementById('modal').classList.add('hidden');
            document.getElementById("consent").checked = false;
            document.getElementById('consent-button').classList.remove('opacity-100');
            document.getElementById('consent-button').classList.add('opacity-50');
            document.getElementById('consent-button').href = "#"
        }

        function validate() {
            if(document.getElementById('consent').checked){
                document.getElementById('consent-button').href = document.getElementById('consent-button').dataset.url;
                document.getElementById('consent-button').classList.remove('opacity-50');
                document.getElementById('consent-button').classList.add('opacity-100');
            }else{
                document.getElementById('consent-button').href = "#"
                document.getElementById('consent-button').classList.remove('opacity-100');
                document.getElementById('consent-button').classList.add('opacity-50');
            }
        }
    </script>
    </body>
</html>

resources/views/error.blade.php
@extends('_layouts.main')

@section('content')
    <div class="rounded-md bg-red-100 p-4 w-full mx-auto mb-6">
        <div class="flex">
            <div class="flex-shrink-0">
                <!-- Heroicon name: x-circle -->
                <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
                </svg>
            </div>
            <div class="ml-3">
                <h3 class="font-medium text-red-800">
                    An error ocurred.
                </h3>
                <div class="mt-2 text-sm text-red-700">
                    <ul class="list-disc pl-5 space-y-1">
                        <li>You are trying to do an illegal operation.</li>
                        <li>Your IP ({{ request()->ip() }}) was registered.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/faq-auth.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Trustee Registration Portal</title>

    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body class="antialiased">
<!--
This example requires Tailwind CSS v2.0+

This example requires some changes to your config:

```
// tailwind.config.js
const colors = require('tailwindcss/colors')

module.exports = {
// ...
theme: {
  extend: {
    colors: {
      lime: colors.lime,
    }
  }
},
plugins: [
  // ...
  require('@tailwindcss/forms'),
]
}
```
-->
<div class="h-screen flex overflow-hidden bg-gray-100">
    <div class="hidden lg:flex lg:flex-shrink-0">
        <div class="flex flex-col w-64">
            <!-- Sidebar component, swap this element with another sidebar if you like -->
            <div class="flex flex-col flex-grow bg-lime-700 pt-5 pb-4 overflow-y-auto">
                @include('_menu')
            </div>
        </div>
    </div>

    <div class="flex-1 overflow-auto focus:outline-none" tabindex="0">

        <main class="flex-1 relative pb-8 z-0 overflow-y-auto">
            <!-- Page header -->
            <div class="bg-white shadow">
                <div class="px-4 sm:px-6 lg:max-w-6xl lg:mx-auto lg:px-8">
                    <div class="py-6 md:flex md:items-center md:justify-between lg:border-t lg:border-gray-200">
                        <div class="flex-1 min-w-0">
                            <!-- Profile -->
                            <div class="flex items-center justify-between">
                                <div>
                                    <img src="{{ asset('images/logo.jpg') }}" alt="">
                                </div>

                                <div class="flex items-center">
                                        <span class="inline-flex items-center justify-center h-14 w-14 rounded-full bg-gray-500">
                                          <span class="text-xl font-medium leading-none text-white">{{ Auth::user()->initials }}</span>
                                        </span>

                                    <div>
                                        <div class="flex items-center">
                                            <h1 class="ml-3 text-2xl font-light leading-7 text-gray-700 sm:leading-7 sm:truncate">
                                                {{ Auth::user()->name }}
                                            </h1>
                                        </div>
                                        <dl class="mt-6 flex flex-col sm:ml-3 sm:mt-1 sm:flex-row sm:flex-wrap">
                                            <dd class="mt-3 flex items-center text-sm text-gray-500 font-medium sm:mr-6 sm:mt-0 capitalize">
                                                Investor number {{ Auth::user()->investor_number }}
                                            </dd>
                                        </dl>
                                    </div>


                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="p-6">
                @if($questions->isEmpty())
                    <div class="flex items-center text-orange-600">
                        <svg class="h-6 w-6 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                        </svg>

                        <div>
                            No questions found.
                        </div>
                    </div>
                @else

                    <div>

                        <h1 class="text-xl font-semibold text-lime-700 mb-6">Frequently Asked Questions</h1>

                        <div class="">
                            <ul>
                                @foreach($questions as $question)
                                    <li class="shadow rounded mb-6 bg-white">
                                        <div class="relative focus-within:ring-2 focus-within:ring-indigo-500">
                                            <h3 class="p-4 text bg-gray-100 font-semibold border-b border-gray-200 text-gray-800">
                                                {{ $question->question }}
                                            </h3>
                                            <div class="p-4 text-sm text-gray-500">
                                                {!! $question->trixRichText->first()->content !!}
                                            </div>
                                        </div>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>

                @endif

            </div>
        </main>
    </div>
</div>


</body>
</html>